version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    networks:
      - lingo-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - lingo-network
    command: start-dev

  db:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - lingo-network

networks:
  lingo-network:
    external: true
